export interface PostMortemDocument {
  id: string;
  eventId: string;
  eventTitle: string;
  clubId: string;
  retrospectiveText: string;
  createdAtIso: string;
}

export interface SynthesizedWikiPayload {
  clubId: string;
  semesterLabel: string;
  wikiMarkdown: string;
  extractedInsightsCount: number;
  processedPostMortemsCount: number;
}

/**
 * Constructs LLM prompt payload instructing the model to synthesize historical post-mortems into a 10-point best practices manual.
 */
export function buildPostMortemExtractionPrompt(
  clubName: string,
  postMortems: PostMortemDocument[],
): string {
  const concatenatedRetros = postMortems
    .map(
      (pm, index) =>
        `--- Retrospective ${index + 1}: ${pm.eventTitle} ---\n${pm.retrospectiveText}`,
    )
    .join("\n\n");

  return `
You are an executive advisor analyzing historical event retrospectives for "${clubName}".

Analyze the following ${postMortems.length} post-mortem reports accumulated over the past semester:

${concatenatedRetros}

Synthesize these event retrospectives into a concise, 10-point "Best Practices" manual for future student leaders.
Format your output strictly in Markdown with clear category headers and actionable bullet points.
  `.trim();
}

/**
 * Formats AI-generated response into structured Wiki document record for storage.
 */
export function formatSynthesizedWikiRecord(
  clubId: string,
  semesterLabel: string,
  llmResponseMarkdown: string,
  processedPostMortemsCount: number,
): SynthesizedWikiPayload {
  // Count bullet points in generated markdown to track extracted insights
  const bulletMatches = llmResponseMarkdown.match(/^[\s]*[-*•]\s+/gm);
  const extractedInsightsCount = bulletMatches ? bulletMatches.length : 10;

  const formattedMarkdown = `
# How to Successfully Run This Club
*Generated by AI from ${processedPostMortemsCount} past event post-mortems (${semesterLabel})*

${llmResponseMarkdown.trim()}
  `.trim();

  return {
    clubId,
    semesterLabel,
    wikiMarkdown: formattedMarkdown,
    extractedInsightsCount,
    processedPostMortemsCount,
  };
}
