import { describe, it, expect } from "vitest";
import {
  buildPostMortemExtractionPrompt,
  formatSynthesizedWikiRecord,
  PostMortemDocument,
} from "./postMortemExtractor";

describe("Implement Automated Event Post-Mortem LLM Extraction Suite (#4410)", () => {
  const sampleRetros: PostMortemDocument[] = [
    {
      id: "pm_1",
      eventId: "evt_hackathon",
      eventTitle: "Fall Hackathon",
      clubId: "club_cs",
      retrospectiveText:
        "Food arrived 30 minutes late. Next time order pizza 2 hours before cutoff.",
      createdAtIso: "2026-05-10T10:00:00Z",
    },
    {
      id: "pm_2",
      eventId: "evt_expo",
      eventTitle: "Tech Expo",
      clubId: "club_cs",
      retrospectiveText:
        "A/V microphones cut out during keynote. Always test microphones 1 hour prior.",
      createdAtIso: "2026-06-12T14:00:00Z",
    },
  ];

  it("builds structured LLM synthesis prompt including past retrospective logs", () => {
    const prompt = buildPostMortemExtractionPrompt("Computer Science Society", sampleRetros);

    expect(prompt).toContain("Computer Science Society");
    expect(prompt).toContain("Analyze the following 2 post-mortem reports");
    expect(prompt).toContain("Food arrived 30 minutes late.");
    expect(prompt).toContain("Always test microphones 1 hour prior.");
    expect(prompt).toContain(
      'Synthesize these event retrospectives into a concise, 10-point "Best Practices" manual',
    );
  });

  it("formats synthesized LLM output into structured Wiki Markdown payload", () => {
    const mockLlmResponse = `
### Catering & Logistics
- Order food at least 2 hours before cutoff.
- Confirm delivery contacts 24h prior.

### Technical & A/V Setup
- Perform A/V mic testing 1 hour before stage presentations.
    `.trim();

    const record = formatSynthesizedWikiRecord("club_cs", "Spring 2026", mockLlmResponse, 2);

    expect(record.clubId).toBe("club_cs");
    expect(record.semesterLabel).toBe("Spring 2026");
    expect(record.processedPostMortemsCount).toBe(2);
    expect(record.extractedInsightsCount).toBe(3);
    expect(record.wikiMarkdown).toContain("# How to Successfully Run This Club");
    expect(record.wikiMarkdown).toContain("Generated by AI from 2 past event post-mortems");
  });
});
