// src/services/eventLogisticsService.ts
import { createClient } from "@/lib/supabase/client";
import {
  EventTask,
  TaskStatus,
  CreateCustomTaskPayload,
} from "@/types/eventLogistics";
import {
  evaluateEventLogisticsRules,
  EvaluateRulesEventInput,
} from "@/lib/eventLogisticsRuleEngine";

export class EventLogisticsService {
  private static getSupabase() {
    return createClient();
  }

  /**
   * Fetch all tasks for an event with assignee profile details.
   */
  static async getEventTasks(eventId: string): Promise<EventTask[]> {
    if (!eventId) return [];
    const supabase = this.getSupabase();

    const { data, error } = await supabase
      .from("event_tasks")
      .select(`
        *,
        assignee:profiles!assignee_id ( id, first_name, last_name, handle, avatar_url )
      `)
      .eq("event_id", eventId)
      .order("is_critical", { ascending: false })
      .order("due_date", { ascending: true });

    if (error) {
      console.error("Error fetching event tasks:", error);
      throw error;
    }

    return (data || []) as EventTask[];
  }

  /**
   * Evaluates logistics rules and synchronizes auto-generated tasks for an event.
   * Gracefully adds missing auto tasks and removes de-triggered auto tasks
   * while preserving custom tasks.
   */
  static async syncAutoGeneratedTasks(
    eventId: string,
    eventData: EvaluateRulesEventInput
  ): Promise<EventTask[]> {
    if (!eventId) return [];
    const supabase = this.getSupabase();

    // 1. Fetch existing tasks
    const existingTasks = await this.getEventTasks(eventId);

    // 2. Evaluate rules
    const { tasksToCreate, taskRuleKeysToRemove } = evaluateEventLogisticsRules(
      { ...eventData, id: eventId },
      existingTasks
    );

    // 3. Remove auto tasks whose conditions no longer apply (unless marked done)
    if (taskRuleKeysToRemove.length > 0) {
      await supabase
        .from("event_tasks")
        .delete()
        .eq("event_id", eventId)
        .eq("is_auto_generated", true)
        .in("task_rule_key", taskRuleKeysToRemove)
        .neq("status", "done");
    }

    // 4. Insert new auto-generated tasks
    if (tasksToCreate.length > 0) {
      const payload = tasksToCreate.map((t) => ({
        event_id: eventId,
        title: t.title,
        description: t.description,
        status: t.status || "todo",
        due_date: t.due_date,
        is_auto_generated: true,
        task_rule_key: t.task_rule_key,
        is_critical: t.is_critical || false,
      }));

      const { error: insertErr } = await supabase.from("event_tasks").insert(payload);
      if (insertErr) {
        console.error("Failed to insert auto-generated tasks:", insertErr);
      }
    }

    return await this.getEventTasks(eventId);
  }

  /**
   * Create a custom logistics task.
   */
  static async createCustomTask(payload: CreateCustomTaskPayload): Promise<EventTask> {
    const supabase = this.getSupabase();

    const insertData = {
      event_id: payload.eventId,
      title: payload.title.trim(),
      description: payload.description?.trim() || null,
      due_date: payload.dueDate || null,
      assignee_id: payload.assigneeId || null,
      is_auto_generated: false,
      is_critical: payload.isCritical || false,
      status: "todo" as TaskStatus,
    };

    const { data, error } = await supabase
      .from("event_tasks")
      .insert(insertData)
      .select(`
        *,
        assignee:profiles!assignee_id ( id, first_name, last_name, handle, avatar_url )
      `)
      .single();

    if (error) {
      console.error("Failed to create custom task:", error);
      throw error;
    }

    return data as EventTask;
  }

  /**
   * Update a task's status.
   */
  static async updateTaskStatus(taskId: string, status: TaskStatus): Promise<void> {
    const supabase = this.getSupabase();
    const { error } = await supabase
      .from("event_tasks")
      .update({ status, updated_at: new Date().toISOString() })
      .eq("id", taskId);

    if (error) throw error;
  }

  /**
   * Update task due date.
   */
  static async updateTaskDueDate(taskId: string, dueDate: string | null): Promise<void> {
    const supabase = this.getSupabase();
    const { error } = await supabase
      .from("event_tasks")
      .update({ due_date: dueDate, updated_at: new Date().toISOString() })
      .eq("id", taskId);

    if (error) throw error;
  }

  /**
   * Assign a task to an executive user.
   */
  static async assignTask(taskId: string, assigneeId: string | null): Promise<void> {
    const supabase = this.getSupabase();
    const { error } = await supabase
      .from("event_tasks")
      .update({ assignee_id: assigneeId, updated_at: new Date().toISOString() })
      .eq("id", taskId);

    if (error) throw error;
  }

  /**
   * Delete a task.
   */
  static async deleteTask(taskId: string): Promise<void> {
    const supabase = this.getSupabase();
    const { error } = await supabase.from("event_tasks").delete().eq("id", taskId);
    if (error) throw error;
  }

  /**
   * Checks if an event is eligible for public publication.
   * Returns false if any critical tasks (e.g. Security Approval) are incomplete.
   */
  static async canPublishEvent(eventId: string): Promise<{ canPublish: boolean; incompleteTasks: EventTask[] }> {
    const tasks = await this.getEventTasks(eventId);
    const incompleteCritical = tasks.filter((t) => t.is_critical && t.status !== "done");

    return {
      canPublish: incompleteCritical.length === 0,
      incompleteTasks: incompleteCritical,
    };
  }

  /**
   * Checks and sends 48-hour email reminders for upcoming tasks.
   */
  static async send48HourReminders(eventId?: string): Promise<number> {
    const supabase = this.getSupabase();
    const now = new Date();
    const in48Hours = new Date(now.getTime() + 48 * 60 * 60 * 1000);

    let query = supabase
      .from("event_tasks")
      .select(`
        id,
        title,
        due_date,
        assignee_id,
        profiles!assignee_id ( email, first_name, last_name )
      `)
      .neq("status", "done")
      .is("reminder_sent_at", null)
      .not("assignee_id", "is", null)
      .lte("due_date", in48Hours.toISOString())
      .gte("due_date", now.toISOString());

    if (eventId) {
      query = query.eq("event_id", eventId);
    }

    const { data: upcoming, error } = await query;
    if (error || !upcoming || upcoming.length === 0) return 0;

    let reminderCount = 0;

    for (const task of upcoming as any[]) {
      const email = task.profiles?.email;
      if (email) {
        try {
          await supabase.functions.invoke("send-email", {
            body: {
              to: email,
              subject: `Reminder: Task "${task.title}" is due soon`,
              text: `Hello ${task.profiles?.first_name || ""}, your assigned task "${task.title}" is due on ${new Date(task.due_date).toLocaleString()}. Please update its status in the Organizer Dashboard.`,
            },
          });
        } catch (e) {
          console.warn("Failed to send reminder email:", e);
        }
      }

      await supabase
        .from("event_tasks")
        .update({ reminder_sent_at: new Date().toISOString() })
        .eq("id", task.id);

      reminderCount++;
    }

    return reminderCount;
  }
}
