/**
 * Module: Radio Mic Frequency Coordination
 * File: src/services/rfFrequencyCoordinationService.ts
 * Scope: Builds a wireless microphone frequency plan against every other
 *        transmitter live in the same venue, and refuses on intermodulation
 *        rather than on spacing alone (#4922).
 *
 * Two mics on the same frequency is the failure everyone expects and the one
 * that almost never reaches an audience, because it is obvious in soundcheck.
 * The failures that do reach an audience are generated by channels that are
 * individually clean.
 *
 * Any two transmitters mix in the front end of a receiver and produce signals
 * that nothing transmitted. For a pair at f1 and f2 the third-order products
 * land at 2·f1 − f2 and 2·f2 − f1. Take 606.000, 608.000 and 610.000 MHz —
 * evenly spaced, 2 MHz apart, tidy on a spreadsheet — and the pair at 606 and
 * 608 puts a product on exactly 610.000. The plan is broken *because* it is
 * evenly spaced, which is the arrangement a human reaches for first.
 *
 * The count matters as much as the arithmetic. Three transmitters generate
 * products from three pairs; ten generate them from forty-five. The thing that
 * can go wrong grows quadratically while the thing being planned grows by one.
 *
 * Two further asymmetries the module is built around:
 *
 * Licensing is a property of the frequency and the day, not of the mic. The
 * same handheld is licence-exempt in one part of the band and an offence in
 * another, and the answer changes when a venue licence lapses. An expired
 * licence removes the capacity here rather than annotating it — a warning
 * printed beside an otherwise clean plan is a warning that gets scrolled past.
 *
 * A plan is only correct relative to everything else live at the same time in
 * the same place. Two committees can each produce a valid internal plan and
 * still put two transmitters on one frequency in adjacent rooms, so every
 * check runs against the union of this plan and every signed-off plan sharing
 * the venue and the window.
 *
 * Frequencies are integer kilohertz throughout. Megahertz floats put 606.1 at
 * 606.0999999999999 and make an exact-hit intermodulation test unreliable in
 * the one case it exists to catch.
 */

export type BandKind = "EXEMPT" | "LICENSED";

export type PlanStatus = "DRAFT" | "SIGNED_OFF" | "VOIDED";

export type AssignmentOutcome =
  | "ASSIGNED"
  | "REFUSED_UNKNOWN_TRANSMITTER"
  | "REFUSED_TRANSMITTER_ALREADY_ASSIGNED"
  | "REFUSED_OUT_OF_TUNING_RANGE"
  | "REFUSED_OUTSIDE_ANY_BAND"
  | "REFUSED_OFF_STEP"
  | "REFUSED_UNLICENSED_BAND"
  | "REFUSED_CO_CHANNEL"
  | "REFUSED_ADJACENT_CHANNEL"
  | "REFUSED_INTERMODULATION"
  | "REFUSED_PLAN_NOT_DRAFT";

export type SignOffOutcome =
  "SIGNED_OFF" | "REFUSED_NO_ASSIGNMENTS" | "REFUSED_ALREADY_SIGNED_OFF" | "REFUSED_LICENCE_LAPSED";

/** A contiguous slice of spectrum with a fixed tuning grid. */
export interface RfBand {
  bandId: string;
  label: string;
  kind: BandKind;
  startKhz: number;
  endKhz: number;
  /** Receivers tune on a grid. A frequency off the grid is not selectable. */
  stepKhz: number;
}

/** A licence is held by a venue for a band over a window, not by a device. */
export interface VenueLicence {
  licenceId: string;
  venueId: string;
  bandId: string;
  validFrom: Date;
  /** Licences lapse in a filing cabinet. Past this instant the band is closed. */
  validUntil: Date;
}

export interface Transmitter {
  transmitterId: string;
  label: string;
  /** What the pack can actually tune to. Clean, legal and untunable is not a frequency. */
  tuningStartKhz: number;
  tuningEndKhz: number;
}

export interface PlanAssignment {
  transmitterId: string;
  frequencyKhz: number;
  assignedAt: Date;
}

export interface FrequencyPlan {
  planId: string;
  venueId: string;
  label: string;
  windowStart: Date;
  windowEnd: Date;
  status: PlanStatus;
  assignments: PlanAssignment[];
  signedOffBy: string | null;
  signedOffAt: Date | null;
}

/**
 * A third-order product landing on a channel in use. `victimKhz` is the channel
 * that will be hit; `sourceAKhz` and `sourceBKhz` are the pair that made it.
 * Reporting the pair is the whole point: "610.000 is unavailable" sends someone
 * hunting, "610.000 collides with the product of 606.000 and 608.000" tells
 * them which of three channels to move.
 */
export interface IntermodulationCollision {
  productKhz: number;
  sourceAKhz: number;
  sourceBKhz: number;
  victimKhz: number;
  /** How far the product sits from the channel it lands on. Zero is an exact hit. */
  offsetKhz: number;
}

export interface SpacingCollision {
  frequencyKhz: number;
  transmitterId: string;
  planId: string;
  separationKhz: number;
}

export interface AssignmentResult {
  outcome: AssignmentOutcome;
  frequencyKhz: number | null;
  bandId: string | null;
  /** Set when the outcome is a co-channel or adjacent-channel refusal. */
  spacing: SpacingCollision | null;
  /** Set when the outcome is an intermodulation refusal. */
  intermodulation: IntermodulationCollision | null;
  detail: string;
}

export interface SignOffResult {
  outcome: SignOffOutcome;
  /** Bands whose licence does not cover the plan window, when sign-off is refused. */
  lapsedBandIds: string[];
  detail: string;
}

/** A frequency already in the air, from this plan or from somebody else's. */
export interface OccupiedChannel {
  frequencyKhz: number;
  transmitterId: string;
  planId: string;
}

/**
 * Two channels closer than this are treated as one. Receivers are not
 * infinitely selective and a filter skirt does not stop at the channel edge.
 */
export const DEFAULT_MIN_SPACING_KHZ = 250;

/**
 * How close a third-order product has to land before it matters. Products do
 * not need to be exact to be audible; the intermodulation trap in the module
 * docs happens to be exact, which is what makes it so easy to build by hand.
 */
export const DEFAULT_INTERMOD_GUARD_KHZ = 100;

export interface CoordinationOptions {
  minSpacingKhz?: number;
  intermodGuardKhz?: number;
}

function windowsOverlap(aStart: Date, aEnd: Date, bStart: Date, bEnd: Date): boolean {
  return aStart.getTime() < bEnd.getTime() && bStart.getTime() < aEnd.getTime();
}

function formatMhz(khz: number): string {
  return (khz / 1000).toFixed(3);
}

export class RfFrequencyCoordinationService {
  private readonly bands = new Map<string, RfBand>();
  private readonly licences = new Map<string, VenueLicence>();
  private readonly transmitters = new Map<string, Transmitter>();
  private readonly plans = new Map<string, FrequencyPlan>();

  private readonly minSpacingKhz: number;
  private readonly intermodGuardKhz: number;

  constructor(options: CoordinationOptions = {}) {
    this.minSpacingKhz = options.minSpacingKhz ?? DEFAULT_MIN_SPACING_KHZ;
    this.intermodGuardKhz = options.intermodGuardKhz ?? DEFAULT_INTERMOD_GUARD_KHZ;
  }

  // ---------------------------------------------------------------------------
  // Registration
  // ---------------------------------------------------------------------------

  registerBand(band: RfBand): void {
    if (band.endKhz <= band.startKhz) {
      throw new Error(`Band ${band.bandId} ends at or before it starts`);
    }
    if (band.stepKhz <= 0) {
      throw new Error(`Band ${band.bandId} has a non-positive tuning step`);
    }
    this.bands.set(band.bandId, { ...band });
  }

  registerLicence(licence: VenueLicence): void {
    if (!this.bands.has(licence.bandId)) {
      throw new Error(`Licence ${licence.licenceId} references unknown band ${licence.bandId}`);
    }
    if (licence.validUntil.getTime() <= licence.validFrom.getTime()) {
      throw new Error(`Licence ${licence.licenceId} expires at or before it starts`);
    }
    this.licences.set(licence.licenceId, { ...licence });
  }

  registerTransmitter(transmitter: Transmitter): void {
    if (transmitter.tuningEndKhz < transmitter.tuningStartKhz) {
      throw new Error(`Transmitter ${transmitter.transmitterId} has an inverted tuning range`);
    }
    this.transmitters.set(transmitter.transmitterId, { ...transmitter });
  }

  createPlan(input: {
    planId: string;
    venueId: string;
    label: string;
    windowStart: Date;
    windowEnd: Date;
  }): FrequencyPlan {
    if (input.windowEnd.getTime() <= input.windowStart.getTime()) {
      throw new Error(`Plan ${input.planId} ends at or before it starts`);
    }
    const plan: FrequencyPlan = {
      planId: input.planId,
      venueId: input.venueId,
      label: input.label,
      windowStart: input.windowStart,
      windowEnd: input.windowEnd,
      status: "DRAFT",
      assignments: [],
      signedOffBy: null,
      signedOffAt: null,
    };
    this.plans.set(plan.planId, plan);
    return { ...plan, assignments: [] };
  }

  getPlan(planId: string): FrequencyPlan | null {
    const plan = this.plans.get(planId);
    return plan ? { ...plan, assignments: plan.assignments.map((a) => ({ ...a })) } : null;
  }

  // ---------------------------------------------------------------------------
  // Spectrum state
  // ---------------------------------------------------------------------------

  /** The band containing a frequency, or null if it falls in no registered band. */
  bandFor(frequencyKhz: number): RfBand | null {
    for (const band of this.bands.values()) {
      if (frequencyKhz >= band.startKhz && frequencyKhz <= band.endKhz) {
        return band;
      }
    }
    return null;
  }

  /**
   * Whether a band may be used at a venue at a given instant. Exempt bands are
   * always open. A licensed band with no covering licence is closed outright:
   * the capacity is gone, not flagged.
   */
  isBandUsable(bandId: string, venueId: string, at: Date): boolean {
    const band = this.bands.get(bandId);
    if (!band) return false;
    if (band.kind === "EXEMPT") return true;
    for (const licence of this.licences.values()) {
      if (licence.venueId !== venueId || licence.bandId !== bandId) continue;
      if (
        at.getTime() >= licence.validFrom.getTime() &&
        at.getTime() < licence.validUntil.getTime()
      ) {
        return true;
      }
    }
    return false;
  }

  /**
   * Every channel this plan has to coexist with: its own assignments plus each
   * signed-off plan sharing the venue and overlapping the window. Voided and
   * draft plans are excluded — a draft is somebody thinking out loud, and
   * reserving spectrum against it would let an abandoned plan block a real one.
   */
  occupiedChannels(planId: string): OccupiedChannel[] {
    const plan = this.plans.get(planId);
    if (!plan) return [];

    const occupied: OccupiedChannel[] = plan.assignments.map((assignment) => ({
      frequencyKhz: assignment.frequencyKhz,
      transmitterId: assignment.transmitterId,
      planId: plan.planId,
    }));

    for (const other of this.plans.values()) {
      if (other.planId === plan.planId) continue;
      if (other.status !== "SIGNED_OFF") continue;
      if (other.venueId !== plan.venueId) continue;
      if (!windowsOverlap(plan.windowStart, plan.windowEnd, other.windowStart, other.windowEnd)) {
        continue;
      }
      for (const assignment of other.assignments) {
        occupied.push({
          frequencyKhz: assignment.frequencyKhz,
          transmitterId: assignment.transmitterId,
          planId: other.planId,
        });
      }
    }

    return occupied;
  }

  // ---------------------------------------------------------------------------
  // Intermodulation
  // ---------------------------------------------------------------------------

  /**
   * Third-order products of every pair drawn from `frequencies`, tested against
   * every frequency in the same set — including the two that produced them,
   * because 2·f1 − f2 for a pair spaced by d lands at f1 − d, which is exactly
   * where a human building an evenly spaced plan puts the next channel.
   *
   * Returns the first collision found, or null. First is enough: the caller is
   * refusing the assignment either way, and one named pair is more actionable
   * than a list.
   */
  findIntermodulation(frequencies: number[]): IntermodulationCollision | null {
    for (let i = 0; i < frequencies.length; i += 1) {
      for (let j = i + 1; j < frequencies.length; j += 1) {
        const f1 = frequencies[i];
        const f2 = frequencies[j];
        const products = [2 * f1 - f2, 2 * f2 - f1];

        for (const product of products) {
          for (const victim of frequencies) {
            // A product sitting on one of its own two sources is arithmetically
            // possible only when f1 === f2, which co-channel already refused.
            const offset = Math.abs(product - victim);
            if (offset < this.intermodGuardKhz) {
              return {
                productKhz: product,
                sourceAKhz: f1,
                sourceBKhz: f2,
                victimKhz: victim,
                offsetKhz: offset,
              };
            }
          }
        }
      }
    }
    return null;
  }

  // ---------------------------------------------------------------------------
  // Assignment
  // ---------------------------------------------------------------------------

  /**
   * Place one transmitter on one frequency. Every refusal below is computed at
   * `at`, so licence expiry is asked about the night of the show rather than
   * the night the plan was drafted.
   */
  assign(planId: string, transmitterId: string, frequencyKhz: number, at: Date): AssignmentResult {
    const plan = this.plans.get(planId);
    if (!plan) {
      return this.refuse("REFUSED_PLAN_NOT_DRAFT", `Plan ${planId} does not exist`);
    }
    if (plan.status !== "DRAFT") {
      return this.refuse(
        "REFUSED_PLAN_NOT_DRAFT",
        `Plan ${planId} is ${plan.status.toLowerCase().replace("_", " ")} and cannot be edited`,
      );
    }

    const transmitter = this.transmitters.get(transmitterId);
    if (!transmitter) {
      return this.refuse("REFUSED_UNKNOWN_TRANSMITTER", `Transmitter ${transmitterId} is unknown`);
    }

    if (plan.assignments.some((a) => a.transmitterId === transmitterId)) {
      return this.refuse(
        "REFUSED_TRANSMITTER_ALREADY_ASSIGNED",
        `Transmitter ${transmitterId} already holds a frequency in plan ${planId}`,
      );
    }

    if (frequencyKhz < transmitter.tuningStartKhz || frequencyKhz > transmitter.tuningEndKhz) {
      return this.refuse(
        "REFUSED_OUT_OF_TUNING_RANGE",
        `${formatMhz(frequencyKhz)} MHz is outside the tuning range of ${transmitter.label} ` +
          `(${formatMhz(transmitter.tuningStartKhz)}–${formatMhz(transmitter.tuningEndKhz)} MHz)`,
      );
    }

    const band = this.bandFor(frequencyKhz);
    if (!band) {
      return this.refuse(
        "REFUSED_OUTSIDE_ANY_BAND",
        `${formatMhz(frequencyKhz)} MHz falls outside every registered band`,
      );
    }

    if ((frequencyKhz - band.startKhz) % band.stepKhz !== 0) {
      return {
        ...this.refuse(
          "REFUSED_OFF_STEP",
          `${formatMhz(frequencyKhz)} MHz is off the ${band.stepKhz} kHz tuning grid of ${band.label}`,
        ),
        bandId: band.bandId,
      };
    }

    if (!this.isBandUsable(band.bandId, plan.venueId, at)) {
      return {
        ...this.refuse(
          "REFUSED_UNLICENSED_BAND",
          `${band.label} is licensed and no licence covers ${plan.venueId} at ${at.toISOString()}`,
        ),
        bandId: band.bandId,
      };
    }

    const occupied = this.occupiedChannels(planId);

    for (const channel of occupied) {
      const separation = Math.abs(channel.frequencyKhz - frequencyKhz);
      if (separation === 0) {
        return {
          ...this.refuse(
            "REFUSED_CO_CHANNEL",
            `${formatMhz(frequencyKhz)} MHz is already used by ${channel.transmitterId} in plan ${channel.planId}`,
          ),
          bandId: band.bandId,
          spacing: {
            frequencyKhz: channel.frequencyKhz,
            transmitterId: channel.transmitterId,
            planId: channel.planId,
            separationKhz: separation,
          },
        };
      }
      if (separation < this.minSpacingKhz) {
        return {
          ...this.refuse(
            "REFUSED_ADJACENT_CHANNEL",
            `${formatMhz(frequencyKhz)} MHz sits ${separation} kHz from ${formatMhz(channel.frequencyKhz)} MHz ` +
              `on ${channel.transmitterId} (plan ${channel.planId}); ${this.minSpacingKhz} kHz is the minimum`,
          ),
          bandId: band.bandId,
          spacing: {
            frequencyKhz: channel.frequencyKhz,
            transmitterId: channel.transmitterId,
            planId: channel.planId,
            separationKhz: separation,
          },
        };
      }
    }

    const candidateSet = [...occupied.map((c) => c.frequencyKhz), frequencyKhz];
    const collision = this.findIntermodulation(candidateSet);
    if (collision) {
      return {
        ...this.refuse(
          "REFUSED_INTERMODULATION",
          `${formatMhz(frequencyKhz)} MHz produces a third-order product at ` +
            `${formatMhz(collision.productKhz)} MHz from the pair ${formatMhz(collision.sourceAKhz)} / ` +
            `${formatMhz(collision.sourceBKhz)} MHz, landing on ${formatMhz(collision.victimKhz)} MHz`,
        ),
        bandId: band.bandId,
        intermodulation: collision,
      };
    }

    plan.assignments.push({ transmitterId, frequencyKhz, assignedAt: at });

    return {
      outcome: "ASSIGNED",
      frequencyKhz,
      bandId: band.bandId,
      spacing: null,
      intermodulation: null,
      detail: `${transmitter.label} assigned ${formatMhz(frequencyKhz)} MHz in ${band.label}`,
    };
  }

  /**
   * Walk the tuning grid for the first frequency this transmitter can hold in
   * this plan. Returns null when the plan has run out of clean spectrum, which
   * happens far earlier than the raw channel count suggests — every assignment
   * removes not just its own channel but the products it forms with each
   * channel already placed.
   */
  suggest(planId: string, transmitterId: string, at: Date): number | null {
    const plan = this.plans.get(planId);
    const transmitter = this.transmitters.get(transmitterId);
    if (!plan || !transmitter || plan.status !== "DRAFT") return null;

    const candidates: number[] = [];
    for (const band of this.bands.values()) {
      if (!this.isBandUsable(band.bandId, plan.venueId, at)) continue;
      const from = Math.max(band.startKhz, transmitter.tuningStartKhz);
      const to = Math.min(band.endKhz, transmitter.tuningEndKhz);
      if (to < from) continue;

      const stepsIn = Math.ceil((from - band.startKhz) / band.stepKhz);
      for (let f = band.startKhz + stepsIn * band.stepKhz; f <= to; f += band.stepKhz) {
        candidates.push(f);
      }
    }

    candidates.sort((a, b) => a - b);

    const occupied = this.occupiedChannels(planId).map((c) => c.frequencyKhz);
    for (const candidate of candidates) {
      const tooClose = occupied.some((f) => Math.abs(f - candidate) < this.minSpacingKhz);
      if (tooClose) continue;
      if (this.findIntermodulation([...occupied, candidate])) continue;
      return candidate;
    }
    return null;
  }

  /** Remove one assignment from a draft plan. Signed-off plans must be reopened first. */
  release(planId: string, transmitterId: string): boolean {
    const plan = this.plans.get(planId);
    if (!plan || plan.status !== "DRAFT") return false;
    const before = plan.assignments.length;
    plan.assignments = plan.assignments.filter((a) => a.transmitterId !== transmitterId);
    return plan.assignments.length !== before;
  }

  // ---------------------------------------------------------------------------
  // Sign-off
  // ---------------------------------------------------------------------------

  /**
   * Freeze the plan and publish its assignments so other plans in the venue can
   * see them. Licences are re-checked across the whole plan window here: a
   * licence that covered every assignment at the moment it was made can still
   * lapse before the show, and the signature is what the show runs on.
   */
  signOff(planId: string, operatorId: string, at: Date): SignOffResult {
    const plan = this.plans.get(planId);
    if (!plan) {
      return { outcome: "REFUSED_NO_ASSIGNMENTS", lapsedBandIds: [], detail: "No such plan" };
    }
    if (plan.status === "SIGNED_OFF") {
      return {
        outcome: "REFUSED_ALREADY_SIGNED_OFF",
        lapsedBandIds: [],
        detail: `Plan ${planId} was signed off by ${plan.signedOffBy}`,
      };
    }
    if (plan.assignments.length === 0) {
      return {
        outcome: "REFUSED_NO_ASSIGNMENTS",
        lapsedBandIds: [],
        detail: `Plan ${planId} has no assignments to sign off`,
      };
    }

    const lapsed = new Set<string>();
    for (const assignment of plan.assignments) {
      const band = this.bandFor(assignment.frequencyKhz);
      if (!band) continue;
      const coversStart = this.isBandUsable(band.bandId, plan.venueId, plan.windowStart);
      const coversEnd = this.isBandUsable(
        band.bandId,
        plan.venueId,
        new Date(plan.windowEnd.getTime() - 1),
      );
      if (!coversStart || !coversEnd) {
        lapsed.add(band.bandId);
      }
    }

    if (lapsed.size > 0) {
      return {
        outcome: "REFUSED_LICENCE_LAPSED",
        lapsedBandIds: [...lapsed].sort(),
        detail: `No licence covers ${[...lapsed].sort().join(", ")} for the whole plan window`,
      };
    }

    plan.status = "SIGNED_OFF";
    plan.signedOffBy = operatorId;
    plan.signedOffAt = at;

    return {
      outcome: "SIGNED_OFF",
      lapsedBandIds: [],
      detail: `Plan ${planId} signed off by ${operatorId} with ${plan.assignments.length} channels`,
    };
  }

  /**
   * Return a signed-off plan to draft. The signature is cleared rather than
   * carried across, because a signature that survives a retune refers to an
   * arrangement that no longer exists.
   */
  reopen(planId: string): boolean {
    const plan = this.plans.get(planId);
    if (!plan || plan.status !== "SIGNED_OFF") return false;
    plan.status = "DRAFT";
    plan.signedOffBy = null;
    plan.signedOffAt = null;
    return true;
  }

  voidPlan(planId: string): boolean {
    const plan = this.plans.get(planId);
    if (!plan || plan.status === "VOIDED") return false;
    plan.status = "VOIDED";
    plan.signedOffBy = null;
    plan.signedOffAt = null;
    return true;
  }

  // ---------------------------------------------------------------------------

  private refuse(outcome: AssignmentOutcome, detail: string): AssignmentResult {
    return {
      outcome,
      frequencyKhz: null,
      bandId: null,
      spacing: null,
      intermodulation: null,
      detail,
    };
  }
}
