// =============================================================================
// Service: Video Caption Translator
// Issue: #3454 - Implement 'Automated Video Caption Translation'
// Description: Parses WebVTT caption files, extracts cue text payloads, translates text
// into target languages ('es', 'zh', 'fr') while strictly preserving timestamp metadata
// integrity ('HH:MM:SS.mmm --> HH:MM:SS.mmm').
// =============================================================================

export interface VttCue {
  id?: string;
  timestampLine: string; // e.g. "00:00:01.000 --> 00:00:04.000"
  startTime: string;
  endTime: string;
  text: string;
}

export interface ParsedVtt {
  header: string;
  cues: VttCue[];
}

export const SUPPORTED_TRANSLATION_LANGUAGES = [
  { code: "en", label: "English", default: true },
  { code: "es", label: "Spanish (Español)" },
  { code: "zh", label: "Mandarin Chinese (中文)" },
  { code: "fr", label: "French (Français)" },
] as const;

export type TargetLanguageCode = "es" | "zh" | "fr" | string;

/**
 * Regex matching WebVTT timestamp line:
 * e.g. "00:00:01.000 --> 00:00:04.000" or "00:01.000 --> 00:04.000"
 */
const VTT_TIMESTAMP_REGEX =
  /^((?:\d{2}:)?\d{2}:\d{2}\.\d{3})\s+-->\s+((?:\d{2}:)?\d{2}:\d{2}\.\d{3})/;

/**
 * Parses a WebVTT formatted string into header and structured cues.
 */
export function parseVttContent(vttContent: string): ParsedVtt {
  const normalized = vttContent.replace(/\r\n/g, "\n");
  const lines = normalized.split("\n");

  let header = "WEBVTT - Auto-generated by CampusConnect AI";
  const cues: VttCue[] = [];

  let i = 0;
  // Collect header until empty line or first cue
  const headerLines: string[] = [];
  while (i < lines.length) {
    const line = lines[i].trim();
    if (
      VTT_TIMESTAMP_REGEX.test(line) ||
      (i + 1 < lines.length && VTT_TIMESTAMP_REGEX.test(lines[i + 1].trim()))
    ) {
      break;
    }
    if (line) {
      headerLines.push(line);
    }
    i++;
  }

  if (headerLines.length > 0) {
    header = headerLines.join("\n");
  }

  // Parse cues
  while (i < lines.length) {
    let line = lines[i].trim();

    if (!line) {
      i++;
      continue;
    }

    let cueId: string | undefined = undefined;

    // Check if line is a cue ID (number/string without -->)
    if (
      !VTT_TIMESTAMP_REGEX.test(line) &&
      i + 1 < lines.length &&
      VTT_TIMESTAMP_REGEX.test(lines[i + 1].trim())
    ) {
      cueId = line;
      i++;
      line = lines[i].trim();
    }

    const match = line.match(VTT_TIMESTAMP_REGEX);
    if (match) {
      const timestampLine = line;
      const startTime = match[1];
      const endTime = match[2];
      i++;

      const textLines: string[] = [];
      while (i < lines.length && lines[i].trim() !== "") {
        textLines.push(lines[i].trim());
        i++;
      }

      cues.push({
        id: cueId,
        timestampLine,
        startTime,
        endTime,
        text: textLines.join(" "),
      });
    } else {
      i++;
    }
  }

  return { header, cues };
}

/**
 * Mock translation dictionary fallback for offline/test environments.
 */
const MOCK_TRANSLATION_DICTIONARY: Record<string, Record<string, string>> = {
  es: {
    "Hello and welcome to the CampusConnect presentation.":
      "Hola y bienvenido a la presentación de CampusConnect.",
    "Today we are discussing campus event management.":
      "Hoy estamos discutiendo la gestión de eventos del campus.",
    "Thank you for attending.": "Gracias por asistir.",
  },
  zh: {
    "Hello and welcome to the CampusConnect presentation.":
      "你好，欢迎来到 CampusConnect 展示演讲。",
    "Today we are discussing campus event management.": "今天我们正在讨论校园活动管理。",
    "Thank you for attending.": "感谢您的出行参与。",
  },
  fr: {
    "Hello and welcome to the CampusConnect presentation.":
      "Bonjour et bienvenue à la présentation CampusConnect.",
    "Today we are discussing campus event management.":
      "Aujourd'hui, nous discutons de la gestion des événements du campus.",
    "Thank you for attending.": "Merci d'avoir participé.",
  },
};

/**
 * Default translation helper function for tests and fallback.
 */
export async function defaultTranslateText(text: string, targetLanguage: string): Promise<string> {
  const langDict = MOCK_TRANSLATION_DICTIONARY[targetLanguage];
  if (langDict && langDict[text]) {
    return langDict[text];
  }
  // Generic translation fallback with language indicator tag
  return `[${targetLanguage.toUpperCase()}] ${text}`;
}

/**
 * Translates a WebVTT content string into a target language while strictly preserving timestamp integrity.
 */
export async function translateVttContent(
  vttContent: string,
  targetLanguage: TargetLanguageCode,
  translateTextFn: (text: string, targetLang: string) => Promise<string> = defaultTranslateText,
): Promise<string> {
  const { header, cues } = parseVttContent(vttContent);

  let outputVtt = `WEBVTT - Translated (${targetLanguage}) by CampusConnect AI\n\n`;

  for (let idx = 0; idx < cues.length; idx++) {
    const cue = cues[idx];
    const translatedText = await translateTextFn(cue.text, targetLanguage);
    const cueIndex = cue.id || String(idx + 1);

    // CRITICAL REQUIREMENT: The timestamp metadata structure must remain untouched!
    outputVtt += `${cueIndex}\n${cue.timestampLine}\n${translatedText.trim()}\n\n`;
  }

  return outputVtt.trim() + "\n";
}

/**
 * Batch translates a base English WebVTT file into multiple target languages (e.g. ['es', 'zh', 'fr']).
 * Returns a record map of language code -> translated VTT content string.
 */
export async function batchTranslateVtt(
  vttContent: string,
  targetLanguages: string[] = ["es", "zh", "fr"],
  translateTextFn: (text: string, targetLang: string) => Promise<string> = defaultTranslateText,
): Promise<Record<string, string>> {
  const results: Record<string, string> = {};

  for (const lang of targetLanguages) {
    results[lang] = await translateVttContent(vttContent, lang, translateTextFn);
  }

  return results;
}
