import { ComboboxOption } from "@/components/ui/Combobox";

export const MAJORS_LIST: string[] = [
  "Aerospace Engineering",
  "African American Studies",
  "Agricultural Business",
  "Agricultural Engineering",
  "Agriculture & Food Systems",
  "Animal Science",
  "Anthropology",
  "Applied Mathematics",
  "Applied Physics",
  "Architectural Engineering",
  "Architecture",
  "Art History",
  "Art & Visual Design",
  "Astronomy & Astrophysics",
  "Atmospheric Science",
  "Biochemistry",
  "Bioengineering",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Sciences",
  "Biophysics",
  "Biotechnology",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classics",
  "Cognitive Science",
  "Communication Studies",
  "Computational Biology",
  "Computer Engineering",
  "Computer Science",
  "Creative Writing",
  "Criminology & Criminal Justice",
  "Cybersecurity",
  "Data Science",
  "Dentistry (Pre-Dental)",
  "Digital Media & Film Production",
  "Earth & Planetary Sciences",
  "Ecology & Evolutionary Biology",
  "Econometrics",
  "Economics",
  "Education (Elementary)",
  "Education (Secondary)",
  "Electrical Engineering",
  "Energy Systems Engineering",
  "Engineering Management",
  "Engineering Physics",
  "English Literature",
  "Entomology",
  "Environmental Engineering",
  "Environmental Science",
  "Environmental Studies",
  "Epidemiology",
  "Exercise Science",
  "Fashion Design",
  "Film & Media Studies",
  "Finance",
  "Fine Arts",
  "Food Science & Technology",
  "Forensic Science",
  "Forestry & Natural Resources",
  "Game Design & Development",
  "Genetics",
  "Geographic Information Systems (GIS)",
  "Geography",
  "Geological Engineering",
  "Geology",
  "Global Health",
  "Graphic Design",
  "Health Administration",
  "Health Informatics",
  "Health Sciences",
  "History",
  "Hospitality & Tourism Management",
  "Human Resource Management",
  "Human-Computer Interaction",
  "Industrial Design",
  "Industrial Engineering",
  "Information Systems",
  "Information Technology",
  "Instructional Design",
  "Integrated Science",
  "Interior Architecture",
  "International Relations",
  "Journalism",
  "Kinesiology",
  "Landscape Architecture",
  "Linguistics",
  "Management Information Systems (MIS)",
  "Marine Biology",
  "Marketing",
  "Materials Science & Engineering",
  "Mathematical Economics",
  "Mathematics",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Media & Communication",
  "Medical Laboratory Science",
  "Medicine (Pre-Med)",
  "Microbiology",
  "Molecular & Cell Biology",
  "Music Performance",
  "Music Theory & Composition",
  "Nanotechnology Engineering",
  "Neuroscience",
  "Nuclear Engineering",
  "Nursing",
  "Nutrition & Dietetics",
  "Oceanography",
  "Operations Research",
  "Optometry (Pre-Optometry)",
  "Organizational Psychology",
  "Petroleum Engineering",
  "Pharmaceutical Sciences",
  "Pharmacy (Pre-Pharmacy)",
  "Philosophy",
  "Philosophy, Politics & Economics (PPE)",
  "Photography",
  "Physical Education",
  "Physical Therapy (Pre-PT)",
  "Physics",
  "Physiology",
  "Political Science",
  "Polymer Science & Engineering",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Policy",
  "Real Estate & Urban Planning",
  "Religious Studies",
  "Robotics & Automation Engineering",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Soil Science",
  "Spanish & Hispanic Studies",
  "Special Education",
  "Speech-Language Pathology",
  "Statistics",
  "Studio Art",
  "Supply Chain Management",
  "Sustainable Energy & Climate Science",
  "System Dynamics",
  "Systems Engineering",
  "Theatre & Performing Arts",
  "Urban & Regional Planning",
  "Veterinary Medicine (Pre-Vet)",
  "Virology",
  "Web Development & UX Design",
];

export const MAJOR_OPTIONS: ComboboxOption[] = MAJORS_LIST.map((major) => ({
  value: major,
  label: major,
}));
