// src/components/__tests__/EventLogisticsChecklist.test.tsx
import React from "react";
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import { EventLogisticsChecklist } from "../EventLogisticsChecklist";

vi.mock("@/lib/supabase/client", () => ({
  createClient: () => ({
    from: () => ({
      select: () => ({
        eq: () => ({
          order: () => ({
            order: () => Promise.resolve({ data: [], error: null }),
          }),
        }),
      }),
    }),
  }),
}));

vi.mock("@/services/eventLogisticsService", () => ({
  EventLogisticsService: {
    syncAutoGeneratedTasks: () =>
      Promise.resolve([
        {
          id: "task-security",
          event_id: "evt-123",
          title: "Submit Campus Security Request Form",
          status: "todo",
          is_auto_generated: true,
          is_critical: true,
        },
        {
          id: "task-catering",
          event_id: "evt-123",
          title: "Finalize Catering Order",
          status: "in_progress",
          is_auto_generated: true,
          is_critical: false,
        },
      ]),
    getEventTasks: () => Promise.resolve([]),
    updateTaskStatus: vi.fn(),
    assignTask: vi.fn(),
    createCustomTask: vi.fn(),
    deleteTask: vi.fn(),
  },
}));

describe("EventLogisticsChecklist Component", () => {
  it("renders publication guard banner when critical task is pending", async () => {
    render(
      <EventLogisticsChecklist
        eventId="evt-123"
        eventData={{ max_attendees: 300, has_catering: true }}
      />
    );

    expect(await screen.findByText(/Publication Guard Active/i)).toBeInTheDocument();
    expect(
      screen.getByText(/Submit Campus Security Request Form/i)
    ).toBeInTheDocument();
  });

  it("renders Add Custom Task button and Kanban column headers", async () => {
    render(
      <EventLogisticsChecklist
        eventId="evt-123"
        eventData={{ max_attendees: 300, has_catering: true }}
      />
    );

    expect(await screen.findByText(/Add Custom Task/i)).toBeInTheDocument();
    expect(screen.getByText(/To Do/i)).toBeInTheDocument();
    expect(screen.getByText(/In Progress/i)).toBeInTheDocument();
    expect(screen.getByText(/Done/i)).toBeInTheDocument();
  });
});
