import { describe, it, expect } from "vitest";
import {
  parseVttContent,
  translateVttContent,
  batchTranslateVtt,
  SUPPORTED_TRANSLATION_LANGUAGES,
} from "../videoCaptionTranslator";

const SAMPLE_ENGLISH_VTT = `WEBVTT - Auto-generated by CampusConnect AI

1
00:00:01.000 --> 00:00:04.000
Hello and welcome to the CampusConnect presentation.

2
00:00:04.500 --> 00:00:09.000
Today we are discussing campus event management.

3
00:00:09.500 --> 00:00:12.000
Thank you for attending.
`;

describe("Video Caption Translator (#3454)", () => {
  it("parses WebVTT header and cue timestamps correctly", () => {
    const { header, cues } = parseVttContent(SAMPLE_ENGLISH_VTT);
    expect(header).toContain("WEBVTT");
    expect(cues).toHaveLength(3);
    expect(cues[0].timestampLine).toBe("00:00:01.000 --> 00:00:04.000");
    expect(cues[0].startTime).toBe("00:00:01.000");
    expect(cues[0].endTime).toBe("00:00:04.000");
    expect(cues[0].text).toBe("Hello and welcome to the CampusConnect presentation.");
  });

  it("strictly preserves timestamp metadata integrity while translating cue text into Spanish", async () => {
    const spanishVtt = await translateVttContent(SAMPLE_ENGLISH_VTT, "es");

    // Check VTT Header
    expect(spanishVtt).toContain("WEBVTT - Translated (es)");

    // CRITICAL: Timestamps MUST remain exact and untouched!
    expect(spanishVtt).toContain("00:00:01.000 --> 00:00:04.000");
    expect(spanishVtt).toContain("00:00:04.500 --> 00:00:09.000");
    expect(spanishVtt).toContain("00:00:09.500 --> 00:00:12.000");

    // Check translated content
    expect(spanishVtt).toContain("Hola y bienvenido a la presentación de CampusConnect.");
  });

  it("batch translates English VTT into Spanish, Mandarin, and French variants", async () => {
    const translations = await batchTranslateVtt(SAMPLE_ENGLISH_VTT, ["es", "zh", "fr"]);

    expect(Object.keys(translations)).toEqual(["es", "zh", "fr"]);

    // Spanish
    expect(translations.es).toContain("00:00:01.000 --> 00:00:04.000");
    expect(translations.es).toContain("Hola y bienvenido");

    // Mandarin Chinese
    expect(translations.zh).toContain("00:00:01.000 --> 00:00:04.000");
    expect(translations.zh).toContain("你好，欢迎来到");

    // French
    expect(translations.fr).toContain("00:00:01.000 --> 00:00:04.000");
    expect(translations.fr).toContain("Bonjour et bienvenue");
  });

  it("exposes supported translation languages array", () => {
    const codes = SUPPORTED_TRANSLATION_LANGUAGES.map((l) => l.code);
    expect(codes).toContain("en");
    expect(codes).toContain("es");
    expect(codes).toContain("zh");
    expect(codes).toContain("fr");
  });
});
