import { useEffect, useRef, useState } from "react";
import Play from "lucide-react/dist/esm/icons/play";
import { cn } from "@/lib/utils";

interface VideoThumbnailProps {
  /** Static image shown when the video is not playing. */
  thumbnailUrl: string;
  /**
   * Short, low-bitrate `.webm` preview snippet (3s, silent) used for the
   * hover preview. Per issue #1908's data-usage edge case, this should be
   * a tiny compressed snippet generated by the backend, NOT the full MP4.
   */
  previewUrl: string;
  /** Optional link target — clicking the thumbnail navigates here. */
  href?: string;
  /** Accessible label for the thumbnail (e.g. event title). */
  alt: string;
  className?: string;
  /** Aspect ratio enforced on the wrapper. Defaults to 16:9. */
  aspectRatio?: "16/9" | "4/3" | "1/1";
}

/**
 * Detect coarse pointer (touch-first) devices. Per issue #1908's mobile
 * edge case, hover doesn't exist on touch, so the preview is skipped
 * entirely and the user sees only the static thumbnail.
 */
function useHoverCapable(): boolean {
  const [hoverCapable, setHoverCapable] = useState<boolean>(() => {
    if (typeof window === "undefined" || !window.matchMedia) return true;
    return window.matchMedia("(hover: hover) and (pointer: fine)").matches;
  });

  useEffect(() => {
    if (typeof window === "undefined" || !window.matchMedia) return;
    const mql = window.matchMedia("(hover: hover) and (pointer: fine)");
    const onChange = () => setHoverCapable(mql.matches);
    mql.addEventListener("change", onChange);
    return () => mql.removeEventListener("change", onChange);
  }, []);

  return hoverCapable;
}

/**
 * VideoThumbnail — a YouTube-style hover-to-preview component (issue #1908).
 *
 * - Layered: a static <img> underneath, a muted <video> on top.
 * - Default state: video is opacity 0 + paused.
 * - mouseenter / focus: video.play() + fade opacity to 100.
 * - mouseleave / blur: video.pause() + reset currentTime to 0 + fade to 0.
 * - On touch devices (no hover): video stays hidden, only the static
 *   thumbnail renders. This is the issue's "Mobile" edge case.
 * - Clicking the thumbnail navigates to `href` if provided, while still
 *   allowing keyboard users to focus + Enter (anchor element).
 */
export function VideoThumbnail({
  thumbnailUrl,
  previewUrl,
  href,
  alt,
  className,
  aspectRatio = "16/9",
}: VideoThumbnailProps) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const [hovering, setHovering] = useState(false);
  const hoverCapable = useHoverCapable();

  // Stop the video entirely if the user is on a touch device; we don't
  // even render the <video> tag so it never preloads / eats bandwidth.
  const showPreview = hoverCapable && Boolean(previewUrl);

  const handleEnter = () => {
    if (!showPreview) return;
    setHovering(true);
    const v = videoRef.current;
    if (v) {
      // Always start from the beginning so each hover shows the snippet
      // from t=0 — predictable, matches the YouTube behavior.
      v.currentTime = 0;
      const playPromise = v.play();
      if (playPromise && typeof playPromise.catch === "function") {
        // Autoplay can reject (e.g. mobile Safari quirks); swallow — the
        // static thumbnail is still on display underneath.
        playPromise.catch(() => {});
      }
    }
  };

  const handleLeave = () => {
    if (!showPreview) return;
    setHovering(false);
    const v = videoRef.current;
    if (v) {
      v.pause();
      v.currentTime = 0;
    }
  };

  const aspectClass =
    aspectRatio === "4/3"
      ? "aspect-[4/3]"
      : aspectRatio === "1/1"
        ? "aspect-square"
        : "aspect-video";

  const wrapperClassName = cn(
    "group relative block w-full overflow-hidden rounded-xl bg-black",
    aspectClass,
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-orange-base focus-visible:ring-offset-2",
    className,
  );

  const PreviewOverlay = showPreview ? (
    <video
      ref={videoRef}
      src={previewUrl}
      muted
      loop
      playsInline
      preload="none"
      aria-hidden="true"
      data-testid="video-preview"
      className={cn(
        "absolute inset-0 h-full w-full object-cover transition-opacity duration-300",
        hovering ? "opacity-100" : "opacity-0",
      )}
    />
  ) : null;

  const PlayBadge = (
    <div
      className={cn(
        "pointer-events-none absolute right-3 bottom-3 inline-flex items-center gap-1 rounded-full bg-black/70 px-3 py-1.5 font-mono text-[10px] font-bold uppercase text-white transition-opacity duration-300",
        hovering && showPreview ? "opacity-0" : "opacity-100",
      )}
    >
      <Play size={12} aria-hidden="true" />
      <span>Hover to preview</span>
    </div>
  );

  if (href) {
    return (
      <a
        href={href}
        aria-label={`Play preview: ${alt}`}
        data-testid="video-thumbnail"
        onMouseEnter={handleEnter}
        onMouseLeave={handleLeave}
        onFocus={handleEnter}
        onBlur={handleLeave}
        className={wrapperClassName}
      >
        <img
          src={thumbnailUrl}
          alt={alt}
          loading="lazy"
          className="absolute inset-0 h-full w-full object-cover"
        />
        {PreviewOverlay}
        {PlayBadge}
      </a>
    );
  }

  return (
    <div
      role="img"
      aria-label={alt}
      data-testid="video-thumbnail"
      tabIndex={0}
      onMouseEnter={handleEnter}
      onMouseLeave={handleLeave}
      onFocus={handleEnter}
      onBlur={handleLeave}
      className={wrapperClassName}
    >
      <img
        src={thumbnailUrl}
        alt={alt}
        loading="lazy"
        className="absolute inset-0 h-full w-full object-cover"
      />
      {PreviewOverlay}
      {PlayBadge}
    </div>
  );
}
