import React, { useState, useRef, useCallback } from "react";

export interface VideoScrubberProps {
  /** Current playback time in seconds */
  progress: number;
  /** Total video duration in seconds */
  duration: number;
  /** Sprite sheet image URL generated by FFmpeg worker */
  spriteUrl?: string;
  /** Total thumbnails in sprite sheet grid (default: 100) */
  totalThumbnails?: number;
  /** Sprite sheet column count (default: 10) */
  cols?: number;
  /** Sprite sheet row count (default: 10) */
  rows?: number;
  /** Thumbnail preview width in px (default: 160) */
  thumbnailWidth?: number;
  /** Thumbnail preview height in px (default: 90) */
  thumbnailHeight?: number;
  /** Callback fired when user clicks or selects a new time position */
  onSeek: (time: number) => void;
  /** Custom container class */
  className?: string;
}

export interface HoverState {
  isVisible: boolean;
  xPos: number; // Pixels from left edge of scrub bar
  percent: number; // 0 to 1
  time: number; // Seconds
  index: number; // Thumbnail cell index (0 to totalThumbnails-1)
  bgX: number; // Shift X in px
  bgY: number; // Shift Y in px
}

export const VideoScrubber: React.FC<VideoScrubberProps> = ({
  progress,
  duration,
  spriteUrl,
  totalThumbnails = 100,
  cols = 10,
  rows = 10,
  thumbnailWidth = 160,
  thumbnailHeight = 90,
  onSeek,
  className = "",
}) => {
  const barRef = useRef<HTMLDivElement>(null);
  const [hoverState, setHoverState] = useState<HoverState | null>(null);

  const calculateHoverState = useCallback(
    (clientX: number): HoverState | null => {
      if (!barRef.current || duration <= 0) return null;
      const rect = barRef.current.getBoundingClientRect();
      if (rect.width <= 0) return null;

      const offsetX = Math.max(0, Math.min(clientX - rect.left, rect.width));
      const percent = offsetX / rect.width;
      const time = percent * duration;
      const index = Math.min(totalThumbnails - 1, Math.floor(percent * totalThumbnails));

      const col = index % cols;
      const row = Math.floor(index / cols);
      const bgX = col * thumbnailWidth;
      const bgY = row * thumbnailHeight;

      return {
        isVisible: true,
        xPos: offsetX,
        percent,
        time,
        index,
        bgX,
        bgY,
      };
    },
    [duration, totalThumbnails, cols, thumbnailWidth, thumbnailHeight],
  );

  const handlePointerMove = (clientX: number) => {
    const state = calculateHoverState(clientX);
    setHoverState(state);
  };

  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    handlePointerMove(e.clientX);
  };

  const handleMouseEnter = (e: React.MouseEvent<HTMLDivElement>) => {
    handlePointerMove(e.clientX);
  };

  const handleMouseLeave = () => {
    setHoverState(null);
  };

  const handleTouchStart = (e: React.TouchEvent<HTMLDivElement>) => {
    if (e.touches.length > 0) {
      handlePointerMove(e.touches[0].clientX);
    }
  };

  const handleTouchMove = (e: React.TouchEvent<HTMLDivElement>) => {
    if (e.touches.length > 0) {
      handlePointerMove(e.touches[0].clientX);
    }
  };

  const handleTouchEnd = () => {
    if (hoverState) {
      onSeek(hoverState.time);
    }
    setHoverState(null);
  };

  const handleClick = (e: React.MouseEvent<HTMLDivElement>) => {
    const state = calculateHoverState(e.clientX);
    if (state) {
      onSeek(state.time);
    }
  };

  const formatTime = (seconds: number) => {
    if (isNaN(seconds)) return "0:00";
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs < 10 ? "0" : ""}${secs}`;
  };

  const progressPercent =
    duration > 0 ? Math.min(100, Math.max(0, (progress / duration) * 100)) : 0;

  return (
    <div className={`relative w-full select-none ${className}`}>
      {/* Hover Thumbnail Tooltip */}
      {hoverState && hoverState.isVisible && (
        <div
          data-testid="video-scrubber-tooltip"
          style={{
            left: `${hoverState.xPos}px`,
            transform: "translateX(-50%)",
          }}
          className="absolute bottom-full mb-3 z-30 flex flex-col items-center pointer-events-none transition-transform duration-75"
        >
          {/* Thumbnail Box */}
          <div
            className="rounded-lg overflow-hidden border-2 border-white/80 shadow-2xl bg-black"
            style={{ width: `${thumbnailWidth}px`, height: `${thumbnailHeight}px` }}
          >
            {spriteUrl ? (
              <div
                data-testid="scrubber-thumbnail-sprite"
                style={{
                  width: `${thumbnailWidth}px`,
                  height: `${thumbnailHeight}px`,
                  backgroundImage: `url(${spriteUrl})`,
                  backgroundPosition: `-${hoverState.bgX}px -${hoverState.bgY}px`,
                  backgroundSize: `${cols * thumbnailWidth}px ${rows * thumbnailHeight}px`,
                }}
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center bg-gray-900 text-xs text-gray-400 font-mono">
                No Preview
              </div>
            )}
          </div>

          {/* Time Badge */}
          <div className="mt-1 bg-black/90 text-white text-[11px] font-mono font-semibold px-2 py-0.5 rounded shadow">
            {formatTime(hoverState.time)}
          </div>
        </div>
      )}

      {/* Scrub Track */}
      <div
        ref={barRef}
        data-testid="video-scrubber-bar"
        onMouseMove={handleMouseMove}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
        onClick={handleClick}
        className="relative flex items-center h-6 cursor-pointer group py-2"
      >
        {/* Track background */}
        <div className="w-full h-1.5 bg-white/30 rounded-full overflow-hidden transition-all duration-150 group-hover:h-2">
          {/* Progress fill */}
          <div
            className="h-full bg-indigo-500 rounded-full transition-all duration-75"
            style={{ width: `${progressPercent}%` }}
          />
        </div>

        {/* Scrubber Knob */}
        <div
          style={{ left: `${progressPercent}%` }}
          className="absolute top-1/2 -translate-y-1/2 -translate-x-1/2 w-3.5 h-3.5 bg-white rounded-full shadow hover:scale-125 transition-transform opacity-0 group-hover:opacity-100"
        />
      </div>
    </div>
  );
};

export default VideoScrubber;
