-- ============================================================
-- Migration: Lost & Found Image Auto-Tagger (Issue #2912)
--
-- Adds:
--   1. `search_tags` JSONB column to the `lost_items` table.
--   2. `pii_rejected_at` timestamp for audit logging.
--   3. Index on `search_tags` for fast tag-based search.
--   4. RPC `get_lost_items_by_tag(tag TEXT)` for tag-based search.
--
-- Backward compatibility:
--   - Both new columns are nullable / have defaults, so existing
--     lost_items rows and client code continue to work.
-- ============================================================

-- ── Step 1: Add columns to lost_items table ─────────────────────
ALTER TABLE public.lost_items
    ADD COLUMN IF NOT EXISTS search_tags JSONB DEFAULT '[]'::jsonb;

ALTER TABLE public.lost_items
    ADD COLUMN IF NOT EXISTS pii_rejected_at TIMESTAMPTZ;

-- ── Step 2: GIN index for fast tag-search queries ───────────────
CREATE INDEX IF NOT EXISTS idx_lost_items_search_tags
    ON public.lost_items USING GIN (search_tags);

-- ── Step 3: Constraint on search_tags shape ─────────────────────
ALTER TABLE public.lost_items
    DROP CONSTRAINT IF EXISTS check_search_tags_is_array;
ALTER TABLE public.lost_items
    ADD CONSTRAINT check_search_tags_is_array
    CHECK (jsonb_typeof(search_tags) = 'array');

-- ── Step 4: RPC to search lost_items by tag ─────────────────────
CREATE OR REPLACE FUNCTION public.get_lost_items_by_tag(
    p_tag TEXT,
    p_limit INTEGER DEFAULT 20,
    p_offset INTEGER DEFAULT 0
) RETURNS TABLE (
    id UUID,
    title TEXT,
    description TEXT,
    image_url TEXT,
    status TEXT,
    search_tags JSONB,
    created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$ BEGIN
    RETURN QUERY
    SELECT
        li.id,
        li.title,
        li.description,
        li.image_url,
        li.status,
        li.search_tags,
        li.created_at
    FROM public.lost_items li
    WHERE li.search_tags @> to_jsonb(LOWER(p_tag))
       OR li.search_tags @> to_jsonb(p_tag)
    ORDER BY li.created_at DESC
    LIMIT GREATEST(1, LEAST(p_limit, 100))
    OFFSET GREATEST(0, p_offset);
END;
 $$;

COMMENT ON FUNCTION public.get_lost_items_by_tag(TEXT, INTEGER, INTEGER) IS
'Search lost_items by a single tag. Case-insensitive — checks both the lowercased and original tag string. Uses the GIN index on search_tags for O(log n) lookup.';

COMMENT ON COLUMN public.lost_items.search_tags IS
'JSONB array of descriptive tags auto-generated by the image recognition Edge Function (e.g., ["water bottle", "blue", "stickers"]). Users can edit/delete tags before final submission via the ImageAutoTagger component.';

COMMENT ON COLUMN public.lost_items.pii_rejected_at IS
'Timestamp marking when the image was rejected by the PII detection step. NULL for items that passed. Used for audit logging and analytics.';

-- ============================================================
-- End of migration
-- ============================================================
