-- 1. Table to store pending role promotion suggestions generated by heuristics/cron
CREATE TABLE IF NOT EXISTS club_role_promotion_suggestions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    suggested_role TEXT DEFAULT 'committee' NOT NULL CHECK (suggested_role IN ('committee', 'officer', 'lead')),
    events_attended_count INTEGER DEFAULT 0 NOT NULL,
    tasks_completed_count INTEGER DEFAULT 0 NOT NULL,
    reason TEXT NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'approved', 'dismissed')),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(club_id, user_id, suggested_role)
);

-- Index for club leadership dashboards
CREATE INDEX IF NOT EXISTS idx_promotion_suggestions_club_status ON club_role_promotion_suggestions(club_id, status);

-- Enable RLS
ALTER TABLE club_role_promotion_suggestions ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Club Presidents/Officers can view and update promotion suggestions for their club
CREATE POLICY "Club leadership can manage promotion suggestions"
    ON club_role_promotion_suggestions FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM club_memberships cm
            WHERE cm.club_id = club_role_promotion_suggestions.club_id
              AND cm.user_id = auth.uid()
              AND cm.role IN ('president', 'officer', 'admin')
        )
    );

-- 2. Stored function to execute 1-click RBAC role promotion upgrade
CREATE OR REPLACE FUNCTION execute_1click_role_promotion(
    p_suggestion_id UUID
)
RETURNS BOOLEAN AS $$
DECLARE
    v_club_id UUID;
    v_user_id UUID;
    v_target_role TEXT;
BEGIN
    SELECT club_id, user_id, suggested_role INTO v_club_id, v_user_id, v_target_role
    FROM club_role_promotion_suggestions
    WHERE id = p_suggestion_id AND status = 'pending';

    IF NOT FOUND THEN
        RETURN FALSE;
    END IF;

    -- Update or insert upgraded RBAC role in club memberships
    UPDATE club_memberships
    SET role = v_target_role, updated_at = NOW()
    WHERE club_id = v_club_id AND user_id = v_user_id;

    -- Mark suggestion as approved
    UPDATE club_role_promotion_suggestions
    SET status = 'approved', updated_at = NOW()
    WHERE id = p_suggestion_id;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;