-- =============================================================================
-- Migration: Algorithmic Icebreaker Engine
-- Issue: #3269 - Develop an 'Algorithmic Icebreaker' Engine for Networking Events
-- Description: Creates tables to store generated icebreaker suggestions and 
-- user interactions (waves). Includes indexes for fast lookups during live events.
-- =============================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- 1. Icebreaker Connections Table
-- Stores the suggested matches generated by the Edge Function
CREATE TABLE IF NOT EXISTS public.icebreaker_connections (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_id UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    user_a_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    user_b_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    similarity_score NUMERIC NOT NULL CHECK (
        similarity_score >= 0
        AND similarity_score <= 1
    ),
    shared_interests TEXT [] NOT NULL DEFAULT '{}',
    conversation_prompt TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Prevent duplicate suggestions for the same pair in the same event
    UNIQUE(event_id, user_a_id, user_b_id)
);
CREATE INDEX IF NOT EXISTS idx_icebreaker_event_user ON public.icebreaker_connections(event_id, user_a_id);
-- 2. Icebreaker Waves Table
-- Tracks when a user indicates they successfully connected with a suggestion
CREATE TABLE IF NOT EXISTS public.icebreaker_waves (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    connection_id UUID NOT NULL REFERENCES public.icebreaker_connections(id) ON DELETE CASCADE,
    waved_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(connection_id, waved_by)
);
-- =============================================================================
-- Row Level Security (RLS)
-- =============================================================================
ALTER TABLE public.icebreaker_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.icebreaker_waves ENABLE ROW LEVEL SECURITY;
-- Users can view their own icebreaker suggestions for events they are attending
CREATE POLICY "Users can view own icebreakers" ON public.icebreaker_connections FOR
SELECT USING (
        (
            auth.uid() = user_a_id
            OR auth.uid() = user_b_id
        )
        AND EXISTS (
            SELECT 1
            FROM public.event_rsvps er
            WHERE er.event_id = icebreaker_connections.event_id
                AND er.user_id = auth.uid()
                AND er.checked_in = TRUE
        )
    );
-- Users can insert waves for their own connections
CREATE POLICY "Users can wave own connections" ON public.icebreaker_waves FOR
INSERT WITH CHECK (
        auth.uid() = waved_by
        AND EXISTS (
            SELECT 1
            FROM public.icebreaker_connections ic
            WHERE ic.id = icebreaker_waves.connection_id
                AND (
                    ic.user_a_id = auth.uid()
                    OR ic.user_b_id = auth.uid()
                )
        )
    );
CREATE POLICY "Users can view own waves" ON public.icebreaker_waves FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM public.icebreaker_connections ic
            WHERE ic.id = icebreaker_waves.connection_id
                AND (
                    ic.user_a_id = auth.uid()
                    OR ic.user_b_id = auth.uid()
                )
        )
    );
