import ffmpeg from "fluent-ffmpeg";
import fs from "fs";
import path from "path";
import axios from "axios";
import FormData from "form-data";

export async function processVideoToTranscript(
  videoPath,
  resourceId,
  supabaseClient,
  openaiApiKey,
) {
  const outputAudioPath = path.join("/tmp", `${resourceId}.mp3`);

  // 1. Extract audio and compress to 64kbps mono MP3 using ffmpeg
  await new Promise((resolve, reject) => {
    ffmpeg(videoPath)
      .outputOptions(["-vn", "-acodec libmp3lame", "-b:a 64k", "-ac 1"])
      .save(outputAudioPath)
      .on("end", resolve)
      .on("error", reject);
  });

  // 2. Call OpenAI Whisper API with confidence filtering / transcription
  const formData = new FormData();
  formData.append("file", fs.createReadStream(outputAudioPath));
  formData.append("model", "whisper-1");
  formData.append("response_format", "verbose_json");

  const response = await axios.post("https://api.openai.com/v1/audio/transcriptions", formData, {
    headers: {
      Authorization: `Bearer ${openaiApiKey}`,
      ...formData.getHeaders(),
    },
  });

  const transcriptionData = response.data;

  // 3. Convert JSON segments to WebVTT format
  let vttContent = "WEBVTT - Auto-generated by CampusConnect AI\n\n";
  let fullText = "";

  if (transcriptionData.segments) {
    transcriptionData.segments.forEach((seg, index) => {
      // Filter out low-confidence hallucinations if necessary
      if (seg.no_speech_prob && seg.no_speech_prob > 0.6) return;

      const start = formatVttTime(seg.start);
      const end = formatVttTime(seg.end);
      vttContent += `${index + 1}\n${start} --> ${end}\n${seg.text.trim()}\n\n`;
      fullText += `${seg.text} `;
    });
  }

  // 4. Upload .vtt file to Supabase Storage bucket ('event_resources')
  const vttFileName = `${resourceId}.vtt`;
  const { error: uploadError } = await supabaseClient.storage
    .from("event_resources")
    .upload(vttFileName, vttContent, {
      contentType: "text/vtt",
      upsert: true,
    });

  if (uploadError) throw uploadError;

  const { data: publicUrlData } = supabaseClient.storage
    .from("event_resources")
    .getPublicUrl(vttFileName);

  // 5. Insert into 'resource_transcripts' table for Full-Text Search
  await supabaseClient.from("resource_transcripts").upsert(
    {
      resource_id: resourceId,
      transcript_text: fullText.trim(),
      vtt_url: publicUrlData.publicUrl,
    },
    { onConflict: "resource_id" },
  );

  // 6. Trigger secondary Edge Function for Automated Video Caption Translation (Issue #3454)
  try {
    const supabaseUrl = process.env.SUPABASE_URL || "http://localhost:54321";
    await axios.post(
      `${supabaseUrl}/functions/v1/translate-vtt-captions`,
      {
        resourceId,
        vttContent,
        targetLanguages: ["es", "zh", "fr"],
      },
      {
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY || ""}`,
        },
      },
    );
  } catch (translationErr) {
    console.warn(
      "[audioWorker] Secondary caption translation trigger non-fatal error:",
      translationErr.message,
    );
  }

  // Cleanup local temp files
  fs.unlinkSync(outputAudioPath);
  fs.unlinkSync(videoPath);
}

function formatVttTime(seconds) {
  const date = new Date(seconds * 1000);
  const hh = String(date.getUTCHours()).padStart(2, "0");
  const mm = String(date.getUTCMinutes()).padStart(2, "0");
  const ss = String(date.getUTCSeconds()).padStart(2, "0");
  const mmm = String(date.getUTCMilliseconds()).padStart(3, "0");
  return `${hh}:${mm}:${ss}.${mmm}`;
}
