import React, { useState } from 'react';
import { ShieldCheck, QrCode, Key, ArrowRight, X } from 'lucide-react';
import { generateMfaSecret, verifyTotpCode } from '../../services/mfaSecurityEngine';
import { BackupRecoveryCodesView } from './BackupRecoveryCodesView';

interface MfaSetupModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export const MfaSetupModal: React.FC<MfaSetupModalProps> = ({ isOpen, onClose }) => {
    const [mfaData] = useState(generateMfaSecret());
    const [step, setStep] = useState<'qr' | 'verify' | 'recovery'>('qr');
    const [code, setCode] = useState('');
    const [error, setError] = useState<string | null>(null);

    if (!isOpen) return null;

    const handleVerify = () => {
        if (verifyTotpCode(code)) {
            setError(null);
            setStep('recovery');
        } else {
            setError('Invalid 6-digit verification code. Please try again.');
        }
    };

    return (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-md flex items-center justify-center p-4">
            <div className="bg-slate-900 border border-slate-800 rounded-3xl max-w-md w-full p-6 space-y-6 shadow-2xl relative text-slate-100 font-sans">
                <button
                    onClick={onClose}
                    className="absolute top-5 right-5 p-1 rounded-full text-slate-400 hover:text-slate-200 hover:bg-slate-800"
                >
                    <X className="w-4 h-4" />
                </button>

                <div className="flex items-center gap-3 border-b border-slate-800 pb-4">
                    <div className="p-2.5 rounded-2xl bg-indigo-500/10 border border-indigo-500/30 text-indigo-400">
                        <ShieldCheck className="w-5 h-5" />
                    </div>
                    <div>
                        <h3 className="text-base font-bold text-slate-100">Two-Factor Authentication</h3>
                        <p className="text-xs text-slate-400">Secure your CampusConnect account</p>
                    </div>
                </div>

                {step === 'qr' && (
                    <div className="space-y-4 text-center">
                        <div className="p-4 bg-white rounded-2xl w-44 h-44 mx-auto flex items-center justify-center shadow-lg">
                            <QrCode className="w-36 h-36 text-slate-900" />
                        </div>
                        <p className="text-xs text-slate-400">Scan this QR code using Google Authenticator, Authy, or 1Password.</p>

                        <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 flex items-center justify-between text-xs font-mono">
                            <span className="text-slate-500">Secret Key:</span>
                            <span className="text-indigo-400 font-bold">{mfaData.secretKey}</span>
                        </div>

                        <button
                            type="button"
                            onClick={() => setStep('verify')}
                            className="w-full py-3 rounded-2xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-lg shadow-indigo-500/20 flex items-center justify-center gap-2"
                        >
                            <span>Next: Enter Verification Code</span>
                            <ArrowRight className="w-4 h-4" />
                        </button>
                    </div>
                )}

                {step === 'verify' && (
                    <div className="space-y-4">
                        <p className="text-xs text-slate-400">Enter the 6-digit verification code generated by your authenticator app.</p>

                        <input
                            type="text"
                            maxLength={6}
                            value={code}
                            onChange={(e) => setCode(e.target.value)}
                            placeholder="000000"
                            className="w-full text-center text-xl font-mono tracking-widest bg-slate-950 border border-slate-800 rounded-2xl py-3 text-indigo-400 focus:outline-none focus:border-indigo-500"
                        />

                        {error && <p className="text-xs text-rose-400 text-center font-semibold">{error}</p>}

                        <button
                            type="button"
                            onClick={handleVerify}
                            className="w-full py-3 rounded-2xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-lg shadow-indigo-500/20"
                        >
                            Verify & Enable MFA
                        </button>
                    </div>
                )}

                {step === 'recovery' && (
                    <BackupRecoveryCodesView
                        backupCodes={mfaData.backupCodes}
                        onFinish={onClose}
                    />
                )}
            </div>
        </div>
    );
};

export default MfaSetupModal;
